chara_search/urls.py
from django.urls import path
from . import views

app_name = 'chara_search'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='index'),
    path('<int:character_id>/', views.sheet, name='sheet'),
    path('search/', views.SearchResultsView.as_view(), name='search_results')
]

dnd_toolbox/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('chara_search/', include('chara_search.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='index')
]

rp_toolbox/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('chara_search/', include('chara_search.urls')),
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

chara_search/models.py
from django.db import models

# Create your models here.
class Character(models.Model):
    #player = models.ForeignKey(Player, on_delete=models.CASCADE) <--Potential new feature to connect Characters to player
    first_name = models.CharField(max_length=20)
    middle_name = models.CharField(max_length=20,blank=True)
    last_name = models.CharField(max_length=20)
    race = models.CharField(max_length=20)
    character_class = models.CharField(max_length=20)
    display_name = models.CharField(max_length=50,blank=True)

    def __str__(self):
        objtext = self.display_name
        return objtext

    def save(self, *args, **kwargs):
        self.display_name = self.first_name + " " +  self.last_name
        super(Character, self).save(*args,**kwargs)

class Stats(models.Model):
    character = models.ForeignKey(Character, on_delete=models.CASCADE)
    level = models.IntegerField(default=1)
    experience = models.IntegerField(default=0)
    strength = models.IntegerField(default=10)
    constitution = models.IntegerField(default=10)
    dexterity = models.IntegerField(default=10)
    intelligence = models.IntegerField(default=10)
    wisdom = models.IntegerField(default=10)
    charisma = models.IntegerField(default=10)

    def __str__(self):
        objtext = self.character.display_name
        return objtext

home/models.py
from django.db import models

# Create your models here.

chara_search/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.template import loader
from django.forms.models import model_to_dict
from django.views.generic import TemplateView,ListView

from .models import Character, Stats
from django.db.models import Q

# Create your views here.
class HomePageView(TemplateView):
    template_name = "chara_search/index.html"

    def dispatch(self, request, *args, **kwargs):
        self.request.session['query'] = None #Clear the session variable when returning to the home page
        template = loader.get_template("chara_search/index.html")
        return HttpResponse(template.render())

def sheet(request, character_id):
    # @TODO Make sheet iterable so I can make the actual static sheet itself one giant for loop
    sheet = Stats.objects.get(character=character_id)
    #print(sheet.character.first_name)
    template = loader.get_template('chara_search/sheet.html')
    context = {
        'sheet': sheet,
    }
    return HttpResponse(template.render(context,request))

class SearchResultsView(ListView):
    model = Character
    template_name = "chara_search/search_results.html"

    def get_queryset(self):
        query = self.request.GET.get("display_name")
        #print(query)
        self.request.session['query'] = query
        character_list = Character.objects.filter(
            Q(display_name__contains=query)
        )
        return character_list

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.template import loader

# Create your views here.
class HomePageView(TemplateView):
    template_name = 'index.html'

    def dispatch(self, request, *args, **kwargs):
        self.request.session['query'] = None #Clear the session variable when returning to the home page
        template = loader.get_template("index.html")
        return HttpResponse(template.render())

chara_search/templates/chara_search/index.html
<h1>Character Search</h1>

<p>Enter a blank query to return all characters</p>

<form action="{% url 'chara_search:search_results' %}" method="get">
    <input name="display_name" type="text" placeholder="Search...">
</form>

<a href="{% url 'home:index' %}">Return Home</a>

chara_search/templates/chara_search/search_results.html
<h1>Character Search</h1>

<p>Enter a blank query to return all characters</p>
<form action="{% url 'chara_search:search_results' %}" method="get">
    <input name="display_name" type="text" placeholder="Search...">
</form>


<h1>Search results for {{request.session.query}}</h1>

{% if character_list %}
    <ul>
        {% for character in character_list %}
            <li><a href="{% url 'chara_search:sheet' character.id %}">{{ character.display_name }}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No characters are available.</p>
{% endif %}

<a href="{% url 'home:index' %}">Return Home</a>

chara_search/templates/chara_search/sheet.html
<h1>Character Sheet for {{ sheet.character.display_name }}</h1>

<p>First Name: {{sheet.character.first_name}}</p>
<p>Middle Name: {{sheet.character.middle_name}}</p>
<p>Last Name: {{sheet.character.last_name}}</p>
<p>Race: {{sheet.character.race}}</p>
<p>Class: {{sheet.character.character_class}}</p>
<br>
<p>Level: {{sheet.level}}</p>
<p>Current EXP: {{sheet.experience}}</p>
<p>Strength: {{sheet.strength}}</p>
<p>Constitution: {{sheet.constitution}}</p>
<p>Dexterity: {{sheet.dexterity}}</p>
<p>Intelligence: {{sheet.intelligence}}</p>
<p>Wisdom: {{sheet.wisdom}}</p>
<p>Charisma: {{sheet.charisma}}</p>

{% if request.session.query %}
    <a href="/chara_search/search/?display_name={{request.session.query}}">Return to Search results for {{request.session.query}}</a><br>
{% else %}
    <a href="{% url 'chara_search:index' %}">Return to Home</a>
{% endif %}
<br>
<a href="{% url 'home:index' %}">Return Home</a>

home/templates/index.html
<h1>Roleplay Toolkit Home</h1>
<p>This is not a real production-ready project, it's just to fuck around.</p>
<p>If you got here without being provided the link, well, you must be really bored poking around Elastic Beanstalk URLs.</p>

<p>Click on a link to go to that utility:</p>
<a href="{% url 'chara_search:index' %}">Character Search</a>

<p>Useful/External Resources:</p>
<a href="https://www.wizards.com/dnd/dice/dice.htm">Wizards of the Coast DnD Dice Roller</a>